// app/employee/list.jsx
import Link from 'next/link';

export default function EmployeeList() {
  const employees = [
    {
    id: '1',
    firstName: 'Emily',
    lastName: 'Johnson',
    address: '123 Maple Ave, Springfield, USA',
    phone: '+1234567890',
    bio: 'HR professional dedicated to employee well-being.',
    email: 'emily.johnson@x.dummyjson.com',
    avatar: 'https://ik.imagekit.io/jxtjn4hpqj/50382765fd5648c7876d91cc37b27394.png?updatedAt=1748169960405',
    performanceRating: 4,
  },
  {
    id: '2',
    firstName: 'Michael',
    lastName: 'Williams',
    address: '456 Oak St, Metropolis, USA',
    phone: '+1987654321',
    bio: 'Senior engineer with 10+ years of experience.',
    email: 'michael.williams@x.dummyjson.com',
    avatar: 'https://ik.imagekit.io/jxtjn4hpqj/2244af71ad0c25f2cb0a8efa167491fb.png?updatedAt=1748170065374',
    performanceRating: 3,
  },
  {
    id: '3',
    firstName: 'Sophia',
    lastName: 'Brown',
    address: '789 Pine Rd, Gotham, USA',
    phone: '+1122334455',
    bio: 'Sales expert with a passion for customer relationships.',
    email: 'sophia.brown@x.dummyjson.com',
    avatar: 'https://i.imgur.com/8Km9tLL.png',
    performanceRating: 5,
  },
  {
    id: '4',
    firstName: 'James',
    lastName: 'Davis',
    address: '321 Birch Ln, Star City, USA',
    phone: '+12223334444',
    bio: 'Marketing strategist with a focus on digital growth.',
    email: 'james.davis@x.dummyjson.com',
    avatar: 'https://ik.imagekit.io/jxtjn4hpqj/d36865e08723cc1b764e084873e53662.png?updatedAt=1748170137530',
    performanceRating: 4,
  },
  {
    id: '5',
    firstName: 'Emma',
    lastName: 'Miller',
    address: '654 Cedar Ct, Central City, USA',
    phone: '+13334445555',
    bio: 'HR coordinator specializing in onboarding.',
    email: 'emma.miller@x.dummyjson.com',
    avatar: 'https://ik.imagekit.io/jxtjn4hpqj/50382765fd5648c7876d91cc37b27394.png?updatedAt=1748169960405',
    performanceRating: 3,
  },
  {
    id: '6',
    firstName: 'Olivia',
    lastName: 'Wilson',
    address: '852 Spruce St, City, Country',
    phone: '+17778889999',
    bio: 'Marketing specialist with a focus on digital campaigns.',
    email: 'olivia.moore@example.com',
    avatar: 'https://i.imgur.com/2G7z7hH.png',
    performanceRating: 5,
  },
  {
    id: '7',
    firstName: 'Alexander',
    lastName: 'Jones',
    address: '987 Elm St, Smallville, USA',
    phone: '+14445556666',
    bio: 'Experienced sales manager leading regional teams.',
    email: 'alexander.jones@x.dummyjson.com',
    avatar: 'https://i.imgur.com/uvw789.png',
    performanceRating: 2,
  },
  {
    id: '8',
    firstName: 'Ava',
    lastName: 'Taylor',
    address: '159 Walnut St, Gotham, USA',
    phone: '+15556667777',
    bio: 'Creative marketing expert with a focus on social media.',
    email: 'ava.taylor@x.dummyjson.com',
    avatar: 'https://i.imgur.com/xyz1234.png',
    performanceRating: 5,
  },
  {
    id: '9',
    firstName: 'Ethan',
    lastName: 'Martinez',
    address: '753 Maple Ave, Metropolis, USA',
    phone: '+16667778888',
    bio: 'HR professional with a focus on employee engagement.',
    email: 'ethan.martinez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/abc456.png',
    performanceRating: 4,
  },
  {
    id: '10',
    firstName: 'Isabella',
    lastName: 'Anderson',
    address: '246 Oak Rd, Star City, USA',
    phone: '+17778880000',
    bio: 'Engineer passionate about innovative solutions.',
    email: 'isabella.anderson@x.dummyjson.com',
    avatar: 'https://i.imgur.com/def234.png',
    performanceRating: 3,
  },
  {
    id: '11',
    firstName: 'Liam',
    lastName: 'García',
    address: '369 Pine St, Gotham, USA',
    phone: '+18889990000',
    bio: 'Sales executive with excellent client relationships.',
    email: 'liam.garcia@x.dummyjson.com',
    avatar: 'https://i.imgur.com/ghi567.png',
    performanceRating: 2,
  },
  {
    id: '12',
    firstName: 'Mia',
    lastName: 'Rodriguez',
    address: '147 Cedar Ave, Central City, USA',
    phone: '+19990001111',
    bio: 'Marketing coordinator with a focus on digital campaigns.',
    email: 'mia.rodriguez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/jkl678.png',
    performanceRating: 4,
  },
  {
    id: '13',
    firstName: 'Noah',
    lastName: 'Hernandez',
    address: '258 Walnut Rd, Smallville, USA',
    phone: '+17774445555',
    bio: 'HR specialist with experience in talent acquisition.',
    email: 'noah.hernandez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/mno890.png',
    performanceRating: 3,
  },
  {
    id: '14',
    firstName: 'Charlotte',
    lastName: 'Lopez',
    address: '369 Spruce St, Star City, USA',
    phone: '+16665554444',
    bio: 'Engineer focused on software development.',
    email: 'charlotte.lopez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/pqr901.png',
    performanceRating: 5,
  },
  {
    id: '15',
    firstName: 'William',
    lastName: 'Gonzalez',
    address: '480 Elm St, Metropolis, USA',
    phone: '+18887776666',
    bio: 'Sales director with a strategic mindset.',
    email: 'william.gonzalez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/stu234.png',
    performanceRating: 4,
  },
  {
    id: '16',
    firstName: 'Avery',
    lastName: 'Perez',
    address: '591 Oak Ave, Gotham, USA',
    phone: '+17772223333',
    bio: 'Marketing analyst with expertise in SEO.',
    email: 'avery.perez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/vwx567.png',
    performanceRating: 3,
  },
  {
    id: '17',
    firstName: 'Evelyn',
    lastName: 'Sanchez',
    address: '602 Pine Rd, Star City, USA',
    phone: '+19998887777',
    bio: 'HR manager with focus on employee retention.',
    email: 'evelyn.sanchez@x.dummyjson.com',
    avatar: 'https://i.imgur.com/yz0123.png',
    performanceRating: 4,
  },
  {
    id: '18',
    firstName: 'Logan',
    lastName: 'Torres',
    address: '713 Cedar St, Central City, USA',
    phone: '+15553334444',
    bio: 'Engineer specialized in cloud solutions.',
    email: 'logan.torres@x.dummyjson.com',
    avatar: 'https://i.imgur.com/abc890.png',
    performanceRating: 2,
  },
  {
    id: '19',
    firstName: 'Abigail',
    lastName: 'Rivera',
    address: '824 Walnut Ave, Smallville, USA',
    phone: '+17771112222',
    bio: 'Sales associate with a focus on retail markets.',
    email: 'abigail.rivera@x.dummyjson.com',
    avatar: 'https://i.imgur.com/def123.png',
    performanceRating: 3,
  },
  {
    id: '20',
    firstName: 'Jackson',
    lastName: 'Evans',
    address: '935 Maple Rd, Star City, USA',
    phone: '+19997778888',
    bio: 'Marketing manager with a focus on branding.',
    email: 'jackson.evans@x.dummyjson.com',
    avatar: 'https://i.imgur.com/ghi456.png',
    performanceRating: 5,
  },
  ];

  return (
    <div className="p-4 min-h-screen bg-gray-100 dark:bg-gray-900">
      <h1 className="text-2xl font-bold mb-4">Employee Directory</h1>
      <ul className="space-y-3">
        {employees.map((employee) => (
          <li key={employee.id} className="bg-white dark:bg-gray-800 p-3 rounded shadow hover:bg-gray-50 dark:hover:bg-gray-700 transition">
            <Link
              href={`/employee/${employee.id}`}
              className="text-blue-600 hover:underline font-medium"
            >
              {employee.name}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}